import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "hi" | "mr" | "ta" | "te";

export const LANGUAGE_LABELS: Record<Language, string> = {
  en: "English",
  hi: "हिंदी",
  mr: "मराठी",
  ta: "தமிழ்",
  te: "తెలుగు",
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("agroguide_language");
    return (stored as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("agroguide_language", lang);
  };

  useEffect(() => {
    const stored = localStorage.getItem("agroguide_language");
    if (stored && ["en", "hi", "mr", "ta", "te"].includes(stored)) {
      setLanguageState(stored as Language);
    }
  }, []);

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === "object" && k in value) {
        value = value[k];
      } else {
        // Fallback to English
        value = translations.en;
        for (const fallbackKey of keys) {
          if (value && typeof value === "object" && fallbackKey in value) {
            value = value[fallbackKey];
          } else {
            return key; // Return key if not found
          }
        }
        break;
      }
    }
    
    return typeof value === "string" ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Comprehensive translations for farmer-friendly language
const translations: Record<Language, Record<string, any>> = {
  en: {
    // App Navigation
    nav: {
      dashboard: "Dashboard",
      cropRecommendation: "Crop Recommendation",
      diseaseDetection: "Disease Detection",
      governmentSchemes: "Government Schemes",
      settings: "Settings",
      signOut: "Sign Out",
    },
    // Sidebar
    sidebar: {
      appName: "AgroGuide",
      tagline: "Decision Support Platform",
      loggedInAs: "Logged in as",
      version: "Version 1.0",
      collegeProject: "College Major Project",
      agricultureTech: "Agricultural Technology",
      navDescriptions: {
        dashboard: "Overview & Summary",
        cropRecommendation: "Crop Selection Advisory",
        diseaseDetection: "Health Assessment",
        governmentSchemes: "Scheme Eligibility",
        settings: "Profile & Preferences",
      },
    },
    // Dashboard
    dashboard: {
      title: "Dashboard",
      description: "Current status and actionable insights based on your profile",
      location: "Location",
      season: "Season",
      interest: "Interest",
      land: "Land",
      currentRecommendation: "Current Recommendation",
      suitability: "Suitability",
      expectedYield: "Expected Yield",
      estReturns: "Est. Returns",
      cropHealth: "Crop Health",
      schemes: "Schemes",
      available: "Available",
      fullyEligible: "fully eligible",
      recentRecommendations: "Recent Recommendations",
      fieldHealthSummary: "Field Health Summary",
      healthy: "Healthy",
      attention: "Attention",
      atRisk: "At Risk",
      pending: "Pending",
      profileNote: "Based on your profile information — recommendations are personalized for your farm context",
      noProfileMessage: "Please complete your profile setup to view personalized insights.",
      goToSettings: "Go to Settings",
      loading: "Loading dashboard...",
      seasons: {
        kharif: "Kharif (Monsoon)",
        rabi: "Rabi (Winter)",
        zaid: "Zaid (Summer)",
      },
    },
    // Crop Recommendation
    cropRec: {
      title: "Crop Recommendation",
      description: "Provide field conditions to receive crop selection guidance suited to your specific situation",
      soilParams: "Soil Condition Parameters",
      soilType: "Soil Type",
      selectSoilType: "Select soil type",
      soilTypes: {
        clay: "Clay",
        sandy: "Sandy",
        loamy: "Loamy",
        black: "Black Cotton Soil",
        red: "Red Soil",
        alluvial: "Alluvial",
      },
      soilPh: "Soil pH Level",
      nitrogen: "Nitrogen (kg/ha)",
      phosphorus: "Phosphorus (kg/ha)",
      potassium: "Potassium (kg/ha)",
      weatherLocation: "Weather & Location",
      avgRainfall: "Average Rainfall (mm)",
      temperature: "Temperature (°C)",
      humidity: "Humidity (%)",
      region: "Region",
      selectRegion: "Select region",
      regions: {
        central: "Central India",
        north: "North India",
        south: "South India",
        east: "East India",
        west: "West India",
        northeast: "North-East India",
      },
      getRecommendation: "Get Recommendation",
      analyzing: "Analyzing Conditions...",
      recommendedCrop: "Recommended Crop",
      highSuitability: "High Suitability",
      mediumSuitability: "Medium Suitability",
      estProfitability: "Estimated Profitability",
      whyRecommended: "Why This Crop Is Recommended",
      alternatives: "Alternative Options",
      noRecommendation: "No Recommendation Yet",
      noRecommendationDesc: "Fill in the soil and weather parameters on the left, then submit to receive crop recommendations suited to your conditions.",
      range: "Range: 0-14",
    },
    // Disease Detection
    disease: {
      title: "Crop Disease Detection",
      description: "Assess crop health using smartphone images or aerial drone imagery for comprehensive field analysis",
      smartphoneCamera: "Smartphone Camera",
      droneAssessment: "Drone Assessment",
      imageAnalysis: "Image Analysis",
      cropType: "Crop Type (Optional)",
      selectCrop: "Select crop for contextual analysis",
      cropContextHelp: "Selecting a crop helps provide context-aware recommendations",
      uploadImage: "Upload Crop Image",
      uploadHint: "Take a clear photo of the affected plant part",
      supported: "Supported: JPG, PNG (Max 10MB)",
      clickToReplace: "Click to replace image",
      analyzeImage: "Analyze Image",
      newAnalysis: "New Analysis",
      assessmentResult: "Assessment Result",
      cropAppears: "Crop Appears Healthy",
      crop: "Crop",
      issueCategory: "Issue Category",
      affectedArea: "Affected Area",
      expertAdvisory: "Expert Advisory",
      understanding: "Understanding",
      awaitingImage: "Awaiting Image",
      awaitingImageDesc: "Upload a clear image of your crop and click \"Analyze Image\" to receive a detailed health assessment.",
      fieldHealthOverview: "Field Health Overview",
      startDrone: "Start Field Assessment",
      analyzingField: "Analyzing field...",
      zoneStatus: "Zone Status",
      affectedPercentage: "Affected Area",
      riskZones: "Risk Zones",
      zonesPossible: "zones with possible issues",
      identifiedConcerns: "Identified Concerns",
      needsAttention: "Needs attention",
      underMonitoring: "Under monitoring",
      immediateInspection: "Immediate field inspection recommended",
      monitorPreventive: "Monitor and consider preventive measures",
      nextSteps: "Recommended Next Steps",
      conductInspection: "Conduct physical inspection in zones B3, A3, and C3",
      collectSamples: "Collect leaf samples for laboratory confirmation if needed",
      consultExpert: "Consult agricultural extension officer for treatment options",
      noDisease: "No Disease Detected",
      healthyMessage: "Your crop appears healthy. Continue current agricultural practices.",
      severity: {
        low: "Low Severity",
        medium: "Moderate Severity",
        high: "High Severity",
      },
      categories: {
        fungal: "Fungal",
        bacterial: "Bacterial",
        viral: "Viral",
        pest: "Pest",
        healthy: "Healthy",
        nutrient: "Nutrient Deficiency",
        water: "Water Stress",
      },
      crops: {
        rice: "Rice (Paddy)",
        wheat: "Wheat",
        maize: "Maize (Corn)",
        cotton: "Cotton",
        tomato: "Tomato",
        potato: "Potato",
        sugarcane: "Sugarcane",
        groundnut: "Groundnut",
        soybean: "Soybean",
        other: "Other Crop",
      },
    },
    // Government Schemes
    schemes: {
      title: "Government Scheme Eligibility & Advisory",
      subtitle: "Rule-based identification of applicable agricultural schemes based on farmer profile",
      description: "Identify relevant government schemes and programs based on your profile and agricultural activities",
      filterCriteria: "Farmer Profile Parameters",
      filterHelperText: "Schemes are identified based on selected state, crop type, and landholding category.",
      state: "State",
      selectState: "Select state",
      cropType: "Crop Type",
      selectCrop: "Select crop",
      cropTypes: {
        cereals: "Cereals (Rice, Wheat)",
        pulses: "Pulses (Dal, Legumes)",
        oilseeds: "Oilseeds (Soybean, Groundnut)",
        cotton: "Cotton",
        sugarcane: "Sugarcane",
        vegetables: "Vegetables",
        fruits: "Fruits",
        spices: "Spices",
      },
      landholdingCategory: "Landholding Category",
      selectCategory: "Select category",
      landCategories: {
        marginal: "Marginal (<1 hectare)",
        small: "Small (1-2 hectares)",
        semiMedium: "Semi-Medium (2-4 hectares)",
        medium: "Medium (4-10 hectares)",
        large: "Large (>10 hectares)",
      },
      findSchemes: "Find Schemes",
      totalSchemesFound: "Total Schemes Found",
      fullyEligible: "Fully Eligible",
      partialEligibility: "Partial Eligibility",
      resultsExplanation: "The following schemes are applicable based on your provided profile information.",
      applicableSchemes: "Applicable Schemes",
      schemeName: "Scheme Name",
      ministry: "Ministry/Department",
      keyBenefit: "Key Benefit",
      eligibility: "Eligibility",
      eligibilityTooltip: "Eligibility is determined using predefined scheme criteria.",
      eligible: "Fully Eligible",
      partial: "Partially Eligible",
      schemeDetails: "Scheme Details & Eligibility Explanation",
      categoryLabel: "Category",
      eligibilityNotesLabel: "Eligibility Notes",
      whyApplies: "Why this scheme applies to you:",
      keyBenefits: "Key Benefits:",
      applicationProcess: "Application Process:",
      noSearch: "No Search Performed",
      noSearchDesc: "Select your state, crop type, and landholding category above, then click \"Find Schemes\" to view applicable government programs.",
      advisorySummaryTitle: "Advisory Summary",
      advisorySummaryIntro: "Based on your profile, the listed schemes may provide support for your farming activities.",
      advisoryEligibleNote: "You appear fully eligible for {count} scheme(s) that directly match your profile.",
      advisoryCategoriesNote: "These schemes cover areas such as {categories}.",
      advisoryDisclaimer: "We recommend reviewing each scheme's details and consulting your local agricultural office for application guidance.",
      advisoryNote: "This summary is for informational purposes only and does not constitute an entitlement or guarantee of benefits.",
    },
    // Settings
    settings: {
      title: "Settings",
      description: "Manage your farm profile and preferences",
      accountInfo: "Account Information",
      emailAddress: "Email Address",
      accountCreated: "Account created",
      farmContext: "Farm Context",
      state: "State",
      selectState: "Select state",
      district: "District",
      enterDistrict: "Enter district",
      farmingSeason: "Farming Season",
      selectSeason: "Select season",
      landholdingSize: "Landholding Size",
      selectSize: "Select size",
      primaryCrops: "Primary Crops of Interest",
      selected: "Selected",
      saveChanges: "Save Changes",
      saving: "Saving...",
      profileNote: "Based on your profile information, recommendations and insights are personalized for your farm context.",
      seasons: {
        kharif: "Kharif (Monsoon)",
        rabi: "Rabi (Winter)",
        zaid: "Zaid (Summer)",
      },
    },
    // Common
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      cancel: "Cancel",
      save: "Save",
      language: "Language",
      interfaceLanguage: "Interface Language",
    },
    // Status Labels
    status: {
      healthy: "Healthy",
      attention: "Needs Attention",
      risk: "At Risk",
      high: "High",
      medium: "Medium",
      low: "Low",
    },
  },
  hi: {
    // App Navigation
    nav: {
      dashboard: "डैशबोर्ड",
      cropRecommendation: "फसल सिफारिश",
      diseaseDetection: "रोग पहचान",
      governmentSchemes: "सरकारी योजनाएं",
      settings: "सेटिंग्स",
      signOut: "लॉग आउट",
    },
    // Sidebar
    sidebar: {
      appName: "एग्रोगाइड",
      tagline: "कृषि निर्णय सहायता मंच",
      loggedInAs: "लॉग इन",
      version: "संस्करण 1.0",
      collegeProject: "कॉलेज प्रमुख परियोजना",
      agricultureTech: "कृषि प्रौद्योगिकी",
      navDescriptions: {
        dashboard: "अवलोकन और सारांश",
        cropRecommendation: "फसल चयन सलाह",
        diseaseDetection: "स्वास्थ्य मूल्यांकन",
        governmentSchemes: "योजना पात्रता",
        settings: "प्रोफाइल और प्राथमिकताएं",
      },
    },
    // Dashboard
    dashboard: {
      title: "डैशबोर्ड",
      description: "आपकी प्रोफाइल के आधार पर वर्तमान स्थिति और कार्रवाई योग्य जानकारी",
      location: "स्थान",
      season: "मौसम",
      interest: "रुचि",
      land: "भूमि",
      currentRecommendation: "वर्तमान सिफारिश",
      suitability: "उपयुक्तता",
      expectedYield: "अनुमानित उपज",
      estReturns: "अनुमानित आय",
      cropHealth: "फसल स्वास्थ्य",
      schemes: "योजनाएं",
      available: "उपलब्ध",
      fullyEligible: "पूर्ण पात्र",
      recentRecommendations: "हाल की सिफारिशें",
      fieldHealthSummary: "खेत स्वास्थ्य सारांश",
      healthy: "स्वस्थ",
      attention: "ध्यान दें",
      atRisk: "जोखिम में",
      pending: "लंबित",
      profileNote: "आपकी प्रोफाइल जानकारी के आधार पर — सिफारिशें आपके खेत के संदर्भ के अनुसार अनुकूलित हैं",
      noProfileMessage: "व्यक्तिगत जानकारी देखने के लिए कृपया अपनी प्रोफाइल सेटअप पूरी करें।",
      goToSettings: "सेटिंग्स पर जाएं",
      loading: "डैशबोर्ड लोड हो रहा है...",
      seasons: {
        kharif: "खरीफ (मानसून)",
        rabi: "रबी (सर्दी)",
        zaid: "जायद (गर्मी)",
      },
    },
    // Crop Recommendation
    cropRec: {
      title: "फसल सिफारिश",
      description: "अपनी विशेष स्थिति के अनुसार फसल चयन मार्गदर्शन प्राप्त करने के लिए खेत की स्थितियां बताएं",
      soilParams: "मिट्टी की स्थिति मापदंड",
      soilType: "मिट्टी का प्रकार",
      selectSoilType: "मिट्टी का प्रकार चुनें",
      soilTypes: {
        clay: "चिकनी मिट्टी",
        sandy: "रेतीली मिट्टी",
        loamy: "दोमट मिट्टी",
        black: "काली कपास मिट्टी",
        red: "लाल मिट्टी",
        alluvial: "जलोढ़ मिट्टी",
      },
      soilPh: "मिट्टी का पीएच स्तर",
      nitrogen: "नाइट्रोजन (किग्रा/हेक्टेयर)",
      phosphorus: "फास्फोरस (किग्रा/हेक्टेयर)",
      potassium: "पोटाशियम (किग्रा/हेक्टेयर)",
      weatherLocation: "मौसम और स्थान",
      avgRainfall: "औसत वर्षा (मिमी)",
      temperature: "तापमान (°से)",
      humidity: "आर्द्रता (%)",
      region: "क्षेत्र",
      selectRegion: "क्षेत्र चुनें",
      regions: {
        central: "मध्य भारत",
        north: "उत्तर भारत",
        south: "दक्षिण भारत",
        east: "पूर्वी भारत",
        west: "पश्चिम भारत",
        northeast: "उत्तर-पूर्व भारत",
      },
      getRecommendation: "सिफारिश प्राप्त करें",
      analyzing: "विश्लेषण हो रहा है...",
      recommendedCrop: "अनुशंसित फसल",
      highSuitability: "उच्च उपयुक्तता",
      mediumSuitability: "मध्यम उपयुक्तता",
      estProfitability: "अनुमानित लाभ",
      whyRecommended: "यह फसल क्यों अनुशंसित है",
      alternatives: "वैकल्पिक विकल्प",
      noRecommendation: "अभी कोई सिफारिश नहीं",
      noRecommendationDesc: "बाईं ओर मिट्टी और मौसम के मापदंड भरें, फिर अपनी स्थितियों के अनुकूल फसल सिफारिशें प्राप्त करने के लिए सबमिट करें।",
      range: "सीमा: 0-14",
    },
    // Disease Detection
    disease: {
      title: "फसल रोग पहचान",
      description: "व्यापक खेत विश्लेषण के लिए स्मार्टफोन छवियों या ड्रोन इमेजरी का उपयोग करके फसल स्वास्थ्य का आकलन करें",
      smartphoneCamera: "स्मार्टफोन कैमरा",
      droneAssessment: "ड्रोन मूल्यांकन",
      imageAnalysis: "छवि विश्लेषण",
      cropType: "फसल का प्रकार (वैकल्पिक)",
      selectCrop: "संदर्भ विश्लेषण के लिए फसल चुनें",
      cropContextHelp: "फसल चुनने से संदर्भ-जागरूक सिफारिशें मिलती हैं",
      uploadImage: "फसल की छवि अपलोड करें",
      uploadHint: "प्रभावित पौधे के भाग की स्पष्ट तस्वीर लें",
      supported: "समर्थित: JPG, PNG (अधिकतम 10MB)",
      clickToReplace: "बदलने के लिए क्लिक करें",
      analyzeImage: "छवि का विश्लेषण करें",
      newAnalysis: "नया विश्लेषण",
      assessmentResult: "मूल्यांकन परिणाम",
      cropAppears: "फसल स्वस्थ दिखती है",
      crop: "फसल",
      issueCategory: "समस्या श्रेणी",
      affectedArea: "प्रभावित क्षेत्र",
      expertAdvisory: "विशेषज्ञ सलाह",
      understanding: "समझ",
      awaitingImage: "छवि की प्रतीक्षा है",
      awaitingImageDesc: "अपनी फसल की स्पष्ट छवि अपलोड करें और विस्तृत स्वास्थ्य मूल्यांकन प्राप्त करने के लिए \"छवि का विश्लेषण करें\" पर क्लिक करें।",
      fieldHealthOverview: "खेत स्वास्थ्य अवलोकन",
      startDrone: "खेत मूल्यांकन शुरू करें",
      analyzingField: "खेत का विश्लेषण हो रहा है...",
      zoneStatus: "क्षेत्र स्थिति",
      affectedPercentage: "प्रभावित क्षेत्र",
      riskZones: "जोखिम क्षेत्र",
      zonesPossible: "संभावित समस्याओं वाले क्षेत्र",
      identifiedConcerns: "पहचानी गई चिंताएं",
      needsAttention: "ध्यान देने की आवश्यकता",
      underMonitoring: "निगरानी में",
      immediateInspection: "तत्काल खेत निरीक्षण की सिफारिश",
      monitorPreventive: "निगरानी करें और निवारक उपायों पर विचार करें",
      nextSteps: "अनुशंसित अगले कदम",
      conductInspection: "B3, A3 और C3 क्षेत्रों में भौतिक निरीक्षण करें",
      collectSamples: "यदि आवश्यक हो तो प्रयोगशाळा पुष्टि के लिए पत्ती के नमूने एकत्र करें",
      consultExpert: "उपचार विकल्पों के लिए कृषि विस्तार अधिकारी से परामर्श करें",
      noDisease: "कोई रोग नहीं पाया गया",
      healthyMessage: "आपकी फसल स्वस्थ दिखती है। वर्तमान कृषि पद्धतियां जारी रखें।",
      severity: {
        low: "कम गंभीरता",
        medium: "मध्यम गंभीरता",
        high: "उच्च गंभीरता",
      },
      categories: {
        fungal: "फफूंद",
        bacterial: "जीवाणु",
        viral: "विषाणु",
        pest: "कीट",
        healthy: "स्वस्थ",
        nutrient: "पोषक तत्व की कमी",
        water: "पानी का तनाव",
      },
      crops: {
        rice: "धान",
        wheat: "गेहूं",
        maize: "मक्का",
        cotton: "कपास",
        tomato: "टमाटर",
        potato: "आलू",
        sugarcane: "गन्ना",
        groundnut: "मूंगफली",
        soybean: "सोयाबीन",
        other: "अन्य फसल",
      },
    },
    // Government Schemes
    schemes: {
      title: "सरकारी योजना पात्रता एवं सलाह",
      subtitle: "किसान प्रोफाइल के आधार पर लागू कृषि योजनाओं की नियम-आधारित पहचान",
      description: "अपनी प्रोफाइल और कृषि गतिविधियों के आधार पर प्रासंगिक सरकारी योजनाओं की पहचान करें",
      filterCriteria: "किसान प्रोफाइल मापदंड",
      filterHelperText: "योजनाएं चयनित राज्य, फसल प्रकार और भूमि श्रेणी के आधार पर पहचानी जाती हैं।",
      state: "राज्य",
      selectState: "राज्य चुनें",
      cropType: "फसल का प्रकार",
      selectCrop: "फसल चुनें",
      cropTypes: {
        cereals: "अनाज (चावल, गेहूं)",
        pulses: "दालें",
        oilseeds: "तिलहन (सोयाबीन, मूंगफली)",
        cotton: "कपास",
        sugarcane: "गन्ना",
        vegetables: "सब्जियां",
        fruits: "फल",
        spices: "मसाले",
      },
      landholdingCategory: "भूमि श्रेणी",
      selectCategory: "श्रेणी चुनें",
      landCategories: {
        marginal: "सीमांत (<1 हेक्टेयर)",
        small: "छोटा (1-2 हेक्टेयर)",
        semiMedium: "अर्ध-मध्यम (2-4 हेक्टेयर)",
        medium: "मध्यम (4-10 हेक्टेयर)",
        large: "बड़ा (>10 हेक्टेयर)",
      },
      findSchemes: "योजनाएं खोजें",
      totalSchemesFound: "कुल योजनाएं मिलीं",
      fullyEligible: "पूर्ण पात्र",
      partialEligibility: "आंशिक पात्रता",
      resultsExplanation: "आपकी प्रोफाइल जानकारी के आधार पर निम्नलिखित योजनाएं लागू हैं।",
      applicableSchemes: "लागू योजनाएं",
      schemeName: "योजना का नाम",
      ministry: "मंत्रालय/विभाग",
      keyBenefit: "मुख्य लाभ",
      eligibility: "पात्रता",
      eligibilityTooltip: "पात्रता पूर्वनिर्धारित योजना मानदंडों का उपयोग करके निर्धारित की जाती है।",
      eligible: "पूर्ण पात्र",
      partial: "आंशिक पात्र",
      schemeDetails: "योजना विवरण और पात्रता व्याख्या",
      categoryLabel: "श्रेणी",
      eligibilityNotesLabel: "पात्रता नोट्स",
      whyApplies: "यह योजना आप पर क्यों लागू होती है:",
      keyBenefits: "मुख्य लाभ:",
      applicationProcess: "आवेदन प्रक्रिया:",
      noSearch: "कोई खोज नहीं की गई",
      noSearchDesc: "ऊपर अपना राज्य, फसल प्रकार और भूमि श्रेणी चुनें, फिर लागू सरकारी कार्यक्रम देखने के लिए \"योजनाएं खोजें\" पर क्लिक करें।",
      advisorySummaryTitle: "सलाहकार सारांश",
      advisorySummaryIntro: "आपकी प्रोफाइल के आधार पर, सूचीबद्ध योजनाएं आपकी खेती गतिविधियों के लिए सहायता प्रदान कर सकती हैं।",
      advisoryEligibleNote: "आप {count} योजना(ओं) के लिए पूर्ण पात्र प्रतीत होते हैं।",
      advisoryCategoriesNote: "ये योजनाएं {categories} जैसे क्षेत्रों को कवर करती हैं।",
      advisoryDisclaimer: "हम प्रत्येक योजना के विवरण की समीक्षा करने और आवेदन मार्गदर्शन के लिए अपने स्थानीय कृषि कार्यालय से परामर्श करने की सलाह देते हैं।",
      advisoryNote: "यह सारांश केवल सूचनात्मक उद्देश्यों के लिए है और लाभ की गारंटी नहीं है।",
    },
    // Settings
    settings: {
      title: "सेटिंग्स",
      description: "अपनी खेत प्रोफाइल और प्राथमिकताएं प्रबंधित करें",
      accountInfo: "खाता जानकारी",
      emailAddress: "ईमेल पता",
      accountCreated: "खाता बनाया गया",
      farmContext: "खेत संदर्भ",
      state: "राज्य",
      selectState: "राज्य चुनें",
      district: "जिला",
      enterDistrict: "जिला दर्ज करें",
      farmingSeason: "खेती का मौसम",
      selectSeason: "मौसम चुनें",
      landholdingSize: "भूमि का आकार",
      selectSize: "आकार चुनें",
      primaryCrops: "प्राथमिक रुचि की फसलें",
      selected: "चयनित",
      saveChanges: "परिवर्तन सहेजें",
      saving: "सहेजा जा रहा है...",
      profileNote: "आपकी प्रोफाइल जानकारी के आधार पर, सिफारिशें और अंतर्दृष्टि आपके खेत संदर्भ के लिए अनुकूलित हैं।",
      seasons: {
        kharif: "खरीफ (मानसून)",
        rabi: "रबी (सर्दी)",
        zaid: "जायद (गर्मी)",
      },
    },
    // Common
    common: {
      loading: "लोड हो रहा है...",
      error: "त्रुटि",
      success: "सफल",
      cancel: "रद्द करें",
      save: "सहेजें",
      language: "भाषा",
      interfaceLanguage: "इंटरफ़ेस भाषा",
    },
    // Status Labels
    status: {
      healthy: "स्वस्थ",
      attention: "ध्यान दें",
      risk: "जोखिम में",
      high: "उच्च",
      medium: "मध्यम",
      low: "कम",
    },
  },
  mr: {
    // App Navigation
    nav: {
      dashboard: "डॅशबोर्ड",
      cropRecommendation: "पीक शिफारस",
      diseaseDetection: "रोग ओळख",
      governmentSchemes: "सरकारी योजना",
      settings: "सेटिंग्ज",
      signOut: "लॉग आउट",
    },
    // Sidebar
    sidebar: {
      appName: "ॲग्रोगाईड",
      tagline: "शेती निर्णय मदत व्यासपीठ",
      loggedInAs: "लॉग इन",
      version: "आवृत्ती 1.0",
      collegeProject: "महाविद्यालय मुख्य प्रकल्प",
      agricultureTech: "कृषी तंत्रज्ञान",
      navDescriptions: {
        dashboard: "आढावा आणि सारांश",
        cropRecommendation: "पीक निवड सल्ला",
        diseaseDetection: "आरोग्य मूल्यांकन",
        governmentSchemes: "योजना पात्रता",
        settings: "प्रोफाइल आणि प्राधान्ये",
      },
    },
    // Dashboard
    dashboard: {
      title: "डॅशबोर्ड",
      description: "तुमच्या प्रोफाइलवर आधारित सद्य स्थिती आणि कृती योग्य माहिती",
      location: "स्थान",
      season: "हंगाम",
      interest: "आवड",
      land: "जमीन",
      currentRecommendation: "सध्याची शिफारस",
      suitability: "योग्यता",
      expectedYield: "अपेक्षित उत्पादन",
      estReturns: "अंदाजित उत्पन्न",
      cropHealth: "पीक आरोग्य",
      schemes: "योजना",
      available: "उपलब्ध",
      fullyEligible: "पूर्ण पात्र",
      recentRecommendations: "अलीकडील शिफारसी",
      fieldHealthSummary: "शेत आरोग्य सारांश",
      healthy: "निरोगी",
      attention: "लक्ष द्या",
      atRisk: "धोक्यात",
      pending: "प्रलंबित",
      profileNote: "तुमच्या प्रोफाइल माहितीवर आधारित — शिफारसी तुमच्या शेताच्या संदर्भानुसार अनुकूलित आहेत",
      noProfileMessage: "वैयक्तिक माहिती पाहण्यासाठी कृपया तुमची प्रोफाइल सेटअप पूर्ण करा.",
      goToSettings: "सेटिंग्जवर जा",
      loading: "डॅशबोर्ड लोड होत आहे...",
      seasons: {
        kharif: "खरीप (पावसाळा)",
        rabi: "रब्बी (हिवाळा)",
        zaid: "उन्हाळी",
      },
    },
    // Crop Recommendation
    cropRec: {
      title: "पीक शिफारस",
      description: "तुमच्या विशिष्ट परिस्थितीनुसार पीक निवड मार्गदर्शन मिळवण्यासाठी शेताची स्थिती सांगा",
      soilParams: "मातीची स्थिती मापदंड",
      soilType: "मातीचा प्रकार",
      selectSoilType: "मातीचा प्रकार निवडा",
      soilTypes: {
        clay: "चिकणमाती",
        sandy: "वाळूमाती",
        loamy: "गाळयुक्त माती",
        black: "काळी कापूस माती",
        red: "लाल माती",
        alluvial: "गाळाची माती",
      },
      soilPh: "मातीचा पीएच स्तर",
      nitrogen: "नायट्रोजन (किग्रा/हेक्टर)",
      phosphorus: "फॉस्फरस (किग्रा/हेक्टर)",
      potassium: "पोटॅशियम (किग्रा/हेक्टर)",
      weatherLocation: "हवामान आणि स्थान",
      avgRainfall: "सरासरी पाऊस (मिमी)",
      temperature: "तापमान (°से)",
      humidity: "आर्द्रता (%)",
      region: "प्रदेश",
      selectRegion: "प्रदेश निवडा",
      regions: {
        central: "मध्य भारत",
        north: "उत्तर भारत",
        south: "दक्षिण भारत",
        east: "पूर्व भारत",
        west: "पश्चिम भारत",
        northeast: "उत्तर-पूर्व भारत",
      },
      getRecommendation: "शिफारस मिळवा",
      analyzing: "विश्लेषण होत आहे...",
      recommendedCrop: "शिफारस केलेले पीक",
      highSuitability: "उच्च योग्यता",
      mediumSuitability: "मध्यम योग्यता",
      estProfitability: "अंदाजित नफा",
      whyRecommended: "हे पीक का शिफारस केले आहे",
      alternatives: "पर्यायी विकल्प",
      noRecommendation: "अद्याप कोणतीही शिफारस नाही",
      noRecommendationDesc: "डाव्या बाजूला माती आणि हवामान मापदंड भरा, नंतर तुमच्या परिस्थितीनुसार पीक शिफारसी मिळवण्यासाठी सबमिट करा.",
      range: "श्रेणी: 0-14",
    },
    // Disease Detection
    disease: {
      title: "पीक रोग ओळख",
      description: "सर्वसमावेशक शेत विश्लेषणासाठी स्मार्टफोन प्रतिमा किंवा ड्रोन इमेजरी वापरून पीक आरोग्याचे मूल्यांकन करा",
      smartphoneCamera: "स्मार्टफोन कॅमेरा",
      droneAssessment: "ड्रोन मूल्यांकन",
      imageAnalysis: "प्रतिमा विश्लेषण",
      cropType: "पीक प्रकार (पर्यायी)",
      selectCrop: "संदर्भ विश्लेषणासाठी पीक निवडा",
      cropContextHelp: "पीक निवडल्याने संदर्भ-जागरूक शिफारसी मिळतात",
      uploadImage: "पीक प्रतिमा अपलोड करा",
      uploadHint: "प्रभावित वनस्पती भागाचा स्पष्ट फोटो घ्या",
      supported: "समर्थित: JPG, PNG (कमाल 10MB)",
      clickToReplace: "बदलण्यासाठी क्लिक करा",
      analyzeImage: "प्रतिमा विश्लेषण करा",
      newAnalysis: "नवीन विश्लेषण",
      assessmentResult: "मूल्यांकन निकाल",
      cropAppears: "पीक निरोगी दिसते",
      crop: "पीक",
      issueCategory: "समस्या प्रकार",
      affectedArea: "प्रभावित क्षेत्र",
      expertAdvisory: "तज्ञ सल्ला",
      understanding: "समज",
      awaitingImage: "प्रतिमेची प्रतीक्षा आहे",
      awaitingImageDesc: "तुमच्या पिकाची स्पष्ट प्रतिमा अपलोड करा आणि तपशीलवार आरोग्य मूल्यांकन मिळवण्यासाठी \"प्रतिमा विश्लेषण करा\" वर क्लिक करा.",
      fieldHealthOverview: "शेत आरोग्य आढावा",
      startDrone: "शेत मूल्यांकन सुरू करा",
      analyzingField: "शेताचे विश्लेषण होत आहे...",
      zoneStatus: "क्षेत्र स्थिती",
      affectedPercentage: "प्रभावित क्षेत्र",
      riskZones: "धोक्याचे क्षेत्र",
      zonesPossible: "संभाव्य समस्या असलेले क्षेत्र",
      identifiedConcerns: "ओळखलेल्या चिंता",
      needsAttention: "लक्ष देणे आवश्यक",
      underMonitoring: "निरीक्षणाखाली",
      immediateInspection: "तात्काळ शेत तपासणी शिफारसित",
      monitorPreventive: "निरीक्षण करा आणि प्रतिबंधात्मक उपायांचा विचार करा",
      nextSteps: "शिफारस केलेली पुढील पावले",
      conductInspection: "B3, A3 आणि C3 क्षेत्रांमध्ये प्रत्यक्ष तपासणी करा",
      collectSamples: "आवश्यक असल्यास प्रयोगशाळा पुष्टीकरणासाठी पानांचे नमुने गोळा करा",
      consultExpert: "उपचार पर्यायांसाठी कृषी विस्तार अधिकाऱ्यांशी सल्लामसलत करा",
      noDisease: "कोणताही रोग आढळला नाही",
      healthyMessage: "तुमचे पीक निरोगी दिसते. सध्याच्या शेती पद्धती सुरू ठेवा.",
      severity: {
        low: "कमी तीव्रता",
        medium: "मध्यम तीव्रता",
        high: "उच्च तीव्रता",
      },
      categories: {
        fungal: "बुरशी",
        bacterial: "जीवाणू",
        viral: "विषाणू",
        pest: "कीड",
        healthy: "निरोगी",
        nutrient: "पोषक तत्वांची कमतरता",
        water: "पाण्याचा ताण",
      },
      crops: {
        rice: "भात (धान)",
        wheat: "गहू",
        maize: "मका",
        cotton: "कापूस",
        tomato: "टोमॅटो",
        potato: "बटाटा",
        sugarcane: "ऊस",
        groundnut: "भुईमूग",
        soybean: "सोयाबीन",
        other: "इतर पीक",
      },
    },
    // Government Schemes
    schemes: {
      title: "सरकारी योजना पात्रता आणि सल्ला",
      subtitle: "शेतकरी प्रोफाइलवर आधारित लागू कृषी योजनांची नियम-आधारित ओळख",
      description: "तुमच्या प्रोफाइल आणि शेती क्रियाकलापांवर आधारित संबंधित सरकारी योजना ओळखा",
      filterCriteria: "शेतकरी प्रोफाइल मापदंड",
      filterHelperText: "योजना निवडलेले राज्य, पीक प्रकार आणि जमीन श्रेणीवर आधारित ओळखल्या जातात।",
      state: "राज्य",
      selectState: "राज्य निवडा",
      cropType: "पीक प्रकार",
      selectCrop: "पीक निवडा",
      cropTypes: {
        cereals: "धान्य (भात, गहू)",
        pulses: "कडधान्ये",
        oilseeds: "तेलबिया (सोयाबीन, भुईमूग)",
        cotton: "कापूस",
        sugarcane: "ऊस",
        vegetables: "भाज्या",
        fruits: "फळे",
        spices: "मसाले",
      },
      landholdingCategory: "जमीन श्रेणी",
      selectCategory: "श्रेणी निवडा",
      landCategories: {
        marginal: "अल्पभूधारक (<1 हेक्टर)",
        small: "लहान (1-2 हेक्टर)",
        semiMedium: "अर्ध-मध्यम (2-4 हेक्टर)",
        medium: "मध्यम (4-10 हेक्टर)",
        large: "मोठा (>10 हेक्टर)",
      },
      findSchemes: "योजना शोधा",
      totalSchemesFound: "एकूण योजना सापडल्या",
      fullyEligible: "पूर्ण पात्र",
      partialEligibility: "आंशिक पात्रता",
      resultsExplanation: "तुमच्या प्रोफाइल माहितीवर आधारित खालील योजना लागू आहेत.",
      applicableSchemes: "लागू योजना",
      schemeName: "योजनेचे नाव",
      ministry: "मंत्रालय/विभाग",
      keyBenefit: "मुख्य लाभ",
      eligibility: "पात्रता",
      eligibilityTooltip: "पात्रता पूर्वनिर्धारित योजना निकषांचा वापर करून निर्धारित केली जाते.",
      eligible: "पूर्ण पात्र",
      partial: "आंशिक पात्र",
      schemeDetails: "योजना तपशील आणि पात्रता स्पष्टीकरण",
      categoryLabel: "श्रेणी",
      eligibilityNotesLabel: "पात्रता नोट्स",
      whyApplies: "ही योजना तुम्हाला का लागू होते:",
      keyBenefits: "मुख्य लाभ:",
      applicationProcess: "अर्ज प्रक्रिया:",
      noSearch: "कोणतीही शोध केली नाही",
      noSearchDesc: "वर तुमचे राज्य, पीक प्रकार आणि जमीन श्रेणी निवडा, नंतर लागू सरकारी कार्यक्रम पाहण्यासाठी \"योजना शोधा\" वर क्लिक करा.",
      advisorySummaryTitle: "सल्लागार सारांश",
      advisorySummaryIntro: "तुमच्या प्रोफाइलवर आधारित, सूचीबद्ध योजना तुमच्या शेती क्रियाकलापांसाठी मदत देऊ शकतात.",
      advisoryEligibleNote: "तुम्ही {count} योजनांसाठी पूर्णपणे पात्र दिसता.",
      advisoryCategoriesNote: "या योजना {categories} सारख्या क्षेत्रांना कव्हर करतात.",
      advisoryDisclaimer: "आम्ही प्रत्येक योजनेचे तपशील तपासण्याची आणि अर्ज मार्गदर्शनासाठी तुमच्या स्थानिक कृषी कार्यालयाशी संपर्क साधण्याची शिफारस करतो.",
      advisoryNote: "हा सारांश केवळ माहितीच्या उद्देशाने आहे आणि लाभांची हमी देत नाही.",
    },
    // Settings
    settings: {
      title: "सेटिंग्ज",
      description: "तुमची शेत प्रोफाइल आणि प्राधान्ये व्यवस्थापित करा",
      accountInfo: "खाते माहिती",
      emailAddress: "ईमेल पत्ता",
      accountCreated: "खाते तयार केले",
      farmContext: "शेत संदर्भ",
      state: "राज्य",
      selectState: "राज्य निवडा",
      district: "जिल्हा",
      enterDistrict: "जिल्हा प्रविष्ट करा",
      farmingSeason: "शेती हंगाम",
      selectSeason: "हंगाम निवडा",
      landholdingSize: "जमिनीचा आकार",
      selectSize: "आकार निवडा",
      primaryCrops: "मुख्य आवडीची पिके",
      selected: "निवडलेले",
      saveChanges: "बदल जतन करा",
      saving: "जतन होत आहे...",
      profileNote: "तुमच्या प्रोफाइल माहितीवर आधारित, शिफारसी आणि अंतर्दृष्टी तुमच्या शेत संदर्भासाठी अनुकूलित आहेत.",
      seasons: {
        kharif: "खरीप (पावसाळा)",
        rabi: "रब्बी (हिवाळा)",
        zaid: "उन्हाळी",
      },
    },
    // Common
    common: {
      loading: "लोड होत आहे...",
      error: "त्रुटी",
      success: "यशस्वी",
      cancel: "रद्द करा",
      save: "जतन करा",
      language: "भाषा",
      interfaceLanguage: "इंटरफेस भाषा",
    },
    // Status Labels
    status: {
      healthy: "निरोगी",
      attention: "लक्ष द्या",
      risk: "धोक्यात",
      high: "उच्च",
      medium: "मध्यम",
      low: "कमी",
    },
  },
  ta: {
    // App Navigation - Tamil
    nav: {
      dashboard: "டாஷ்போர்டு",
      cropRecommendation: "பயிர் பரிந்துரை",
      diseaseDetection: "நோய் கண்டறிதல்",
      governmentSchemes: "அரசு திட்டங்கள்",
      settings: "அமைப்புகள்",
      signOut: "வெளியேறு",
    },
    // Sidebar
    sidebar: {
      appName: "அக்ரோகைட்",
      tagline: "விவசாய முடிவு ஆதரவு தளம்",
      loggedInAs: "உள்நுழைந்தவர்",
      version: "பதிப்பு 1.0",
      collegeProject: "கல்லூரி முக்கிய திட்டம்",
      agricultureTech: "விவசாய தொழில்நுட்பம்",
      navDescriptions: {
        dashboard: "மேலோட்டம் & சுருக்கம்",
        cropRecommendation: "பயிர் தேர்வு ஆலோசனை",
        diseaseDetection: "ஆரோக்கிய மதிப்பீடு",
        governmentSchemes: "திட்ட தகுதி",
        settings: "சுயவிவரம் & விருப்பத்தேர்வுகள்",
      },
    },
    // Dashboard
    dashboard: {
      title: "டாஷ்போர்டு",
      description: "உங்கள் சுயவிவரத்தின் அடிப்படையில் தற்போதைய நிலை மற்றும் நடவடிக்கை தகவல்கள்",
      location: "இடம்",
      season: "பருவம்",
      interest: "ஆர்வம்",
      land: "நிலம்",
      currentRecommendation: "தற்போதைய பரிந்துரை",
      suitability: "பொருத்தம்",
      expectedYield: "எதிர்பார்க்கப்படும் விளைச்சல்",
      estReturns: "மதிப்பிடப்பட்ட வருவாய்",
      cropHealth: "பயிர் ஆரோக்கியம்",
      schemes: "திட்டங்கள்",
      available: "கிடைக்கும்",
      fullyEligible: "முழு தகுதி",
      recentRecommendations: "சமீபத்திய பரிந்துரைகள்",
      fieldHealthSummary: "வயல் ஆரோக்கிய சுருக்கம்",
      healthy: "ஆரோக்கியம்",
      attention: "கவனம்",
      atRisk: "ஆபத்தில்",
      pending: "நிலுவையில்",
      profileNote: "உங்கள் சுயவிவர தகவலின் அடிப்படையில் — பரிந்துரைகள் உங்கள் பண்ணை சூழலுக்கு தனிப்பயனாக்கப்பட்டுள்ளன",
      noProfileMessage: "தனிப்பயனாக்கப்பட்ட தகவல்களைப் பார்க்க உங்கள் சுயவிவர அமைப்பை நிறைவு செய்யவும்.",
      goToSettings: "அமைப்புகளுக்குச் செல்",
      loading: "டாஷ்போர்டு ஏற்றப்படுகிறது...",
      seasons: {
        kharif: "காரிஃப் (மழைக்காலம்)",
        rabi: "ரபி (குளிர்காலம்)",
        zaid: "ஜாய்த் (கோடைகாலம்)",
      },
    },
    // Crop Recommendation
    cropRec: {
      title: "பயிர் பரிந்துரை",
      description: "உங்கள் குறிப்பிட்ட சூழ்நிலைக்கு ஏற்ற பயிர் தேர்வு வழிகாட்டுதலைப் பெற வயல் நிலைமைகளை வழங்கவும்",
      soilParams: "மண் நிலை அளவுருக்கள்",
      soilType: "மண் வகை",
      selectSoilType: "மண் வகையைத் தேர்ந்தெடுக்கவும்",
      soilTypes: {
        clay: "களிமண்",
        sandy: "மணல் மண்",
        loamy: "வண்டல் மண்",
        black: "கருப்பு பருத்தி மண்",
        red: "சிவப்பு மண்",
        alluvial: "வண்டல் படிவு மண்",
      },
      soilPh: "மண் pH அளவு",
      nitrogen: "நைட்ரஜன் (கிகி/ஹெ)",
      phosphorus: "பாஸ்பரஸ் (கிகி/ஹெ)",
      potassium: "பொட்டாசியம் (கிகி/ஹெ)",
      weatherLocation: "வானிலை & இடம்",
      avgRainfall: "சராசரி மழைப்பொழிவு (மிமீ)",
      temperature: "வெப்பநிலை (°C)",
      humidity: "ஈரப்பதம் (%)",
      region: "பிராந்தியம்",
      selectRegion: "பிராந்தியத்தைத் தேர்ந்தெடுக்கவும்",
      regions: {
        central: "மத்திய இந்தியா",
        north: "வட இந்தியா",
        south: "தென் இந்தியா",
        east: "கிழக்கு இந்தியா",
        west: "மேற்கு இந்தியா",
        northeast: "வடகிழக்கு இந்தியா",
      },
      getRecommendation: "பரிந்துரை பெறு",
      analyzing: "பகுப்பாய்வு செய்யப்படுகிறது...",
      recommendedCrop: "பரிந்துரைக்கப்பட்ட பயிர்",
      highSuitability: "உயர் பொருத்தம்",
      mediumSuitability: "நடுத்தர பொருத்தம்",
      estProfitability: "மதிப்பிடப்பட்ட லாபம்",
      whyRecommended: "இந்த பயிர் ஏன் பரிந்துரைக்கப்படுகிறது",
      alternatives: "மாற்று விருப்பங்கள்",
      noRecommendation: "இன்னும் பரிந்துரை இல்லை",
      noRecommendationDesc: "இடதுபுறத்தில் மண் மற்றும் வானிலை அளவுருக்களை நிரப்பவும், பின்னர் உங்கள் நிலைமைகளுக்கு ஏற்ற பயிர் பரிந்துரைகளைப் பெற சமர்ப்பிக்கவும்.",
      range: "வரம்பு: 0-14",
    },
    // Disease Detection
    disease: {
      title: "பயிர் நோய் கண்டறிதல்",
      description: "விரிவான வயல் பகுப்பாய்வுக்கு ஸ்மார்ட்போன் படங்கள் அல்லது ட்ரோன் படங்களைப் பயன்படுத்தி பயிர் ஆரோக்கியத்தை மதிப்பீடு செய்யுங்கள்",
      smartphoneCamera: "ஸ்மார்ட்போன் கேமரா",
      droneAssessment: "ட்ரோன் மதிப்பீடு",
      imageAnalysis: "பட பகுப்பாய்வு",
      cropType: "பயிர் வகை (விருப்பம்)",
      selectCrop: "சூழல் பகுப்பாய்வுக்கு பயிரைத் தேர்ந்தெடுக்கவும்",
      cropContextHelp: "பயிரைத் தேர்ந்தெடுப்பது சூழல்-விழிப்புணர்வு பரிந்துரைகளை வழங்க உதவுகிறது",
      uploadImage: "பயிர் படத்தை பதிவேற்றவும்",
      uploadHint: "பாதிக்கப்பட்ட தாவர பகுதியின் தெளிவான புகைப்படம் எடுக்கவும்",
      supported: "ஆதரிக்கப்படுவது: JPG, PNG (அதிகபட்சம் 10MB)",
      clickToReplace: "படத்தை மாற்ற கிளிக் செய்யவும்",
      analyzeImage: "படத்தை பகுப்பாய்வு செய்",
      newAnalysis: "புதிய பகுப்பாய்வு",
      assessmentResult: "மதிப்பீட்டு முடிவு",
      cropAppears: "பயிர் ஆரோக்கியமாக தெரிகிறது",
      crop: "பயிர்",
      issueCategory: "பிரச்சனை வகை",
      affectedArea: "பாதிக்கப்பட்ட பகுதி",
      expertAdvisory: "நிபுணர் ஆலோசனை",
      understanding: "புரிதல்",
      awaitingImage: "படத்திற்காக காத்திருக்கிறது",
      awaitingImageDesc: "உங்கள் பயிரின் தெளிவான படத்தை பதிவேற்றி விரிவான ஆரோக்கிய மதிப்பீட்டைப் பெற \"படத்தை பகுப்பாய்வு செய்\" என்பதைக் கிளிக் செய்யவும்.",
      fieldHealthOverview: "வயல் ஆரோக்கிய மேலோட்டம்",
      startDrone: "வயல் மதிப்பீட்டைத் தொடங்கு",
      analyzingField: "வயல் பகுப்பாய்வு செய்யப்படுகிறது...",
      zoneStatus: "மண்டல நிலை",
      affectedPercentage: "பாதிக்கப்பட்ட பகுதி",
      riskZones: "ஆபத்து மண்டலங்கள்",
      zonesPossible: "சாத்தியமான பிரச்சனைகள் உள்ள மண்டலங்கள்",
      identifiedConcerns: "கண்டறியப்பட்ட கவலைகள்",
      needsAttention: "கவனம் தேவை",
      underMonitoring: "கண்காணிப்பில்",
      immediateInspection: "உடனடி வயல் ஆய்வு பரிந்துரைக்கப்படுகிறது",
      monitorPreventive: "கண்காணித்து தடுப்பு நடவடிக்கைகளை பரிசீலிக்கவும்",
      nextSteps: "பரிந்துரைக்கப்பட்ட அடுத்த படிகள்",
      conductInspection: "B3, A3, மற்றும் C3 மண்டலங்களில் உடல் ஆய்வு நடத்தவும்",
      collectSamples: "தேவைப்பட்டால் ஆய்வக உறுதிப்படுத்தலுக்கு இலை மாதிரிகளை சேகரிக்கவும்",
      consultExpert: "சிகிச்சை விருப்பங்களுக்கு விவசாய விரிவாக்க அதிகாரியை அணுகவும்",
      noDisease: "நோய் கண்டறியப்படவில்லை",
      healthyMessage: "உங்கள் பயிர் ஆரோக்கியமாக தெரிகிறது. தற்போதைய விவசாய நடைமுறைகளைத் தொடரவும்.",
      severity: {
        low: "குறைந்த தீவிரம்",
        medium: "மிதமான தீவிரம்",
        high: "அதிக தீவிரம்",
      },
      categories: {
        fungal: "பூஞ்சை",
        bacterial: "பாக்டீரியா",
        viral: "வைரஸ்",
        pest: "பூச்சி",
        healthy: "ஆரோக்கியம்",
        nutrient: "ஊட்டச்சத்து குறைபாடு",
        water: "நீர் அழுத்தம்",
      },
      crops: {
        rice: "நெல்",
        wheat: "கோதுமை",
        maize: "மக்காச்சோளம்",
        cotton: "பருத்தி",
        tomato: "தக்காளி",
        potato: "உருளைக்கிழங்கு",
        sugarcane: "கரும்பு",
        groundnut: "நிலக்கடலை",
        soybean: "சோயாபீன்",
        other: "பிற பயிர்",
      },
    },
    // Government Schemes
    schemes: {
      title: "அரசு திட்ட தகுதி & ஆலோசனை",
      subtitle: "விவசாயி சுயவிவரத்தின் அடிப்படையில் பொருந்தக்கூடிய விவசாய திட்டங்களின் விதி-அடிப்படையிலான அடையாளம்",
      description: "உங்கள் சுயவிவரம் மற்றும் விவசாய நடவடிக்கைகளின் அடிப்படையில் தொடர்புடைய அரசு திட்டங்களை அடையாளம் காணுங்கள்",
      filterCriteria: "விவசாயி சுயவிவர அளவுருக்கள்",
      filterHelperText: "திட்டங்கள் தேர்ந்தெடுக்கப்பட்ட மாநிலம், பயிர் வகை மற்றும் நிலவுடைமை வகையின் அடிப்படையில் அடையாளம் காணப்படுகின்றன.",
      state: "மாநிலம்",
      selectState: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
      cropType: "பயிர் வகை",
      selectCrop: "பயிரைத் தேர்ந்தெடுக்கவும்",
      cropTypes: {
        cereals: "தானியங்கள் (நெல், கோதுமை)",
        pulses: "பருப்பு வகைகள்",
        oilseeds: "எண்ணெய் வித்துக்கள் (சோயாபீன், நிலக்கடலை)",
        cotton: "பருத்தி",
        sugarcane: "கரும்பு",
        vegetables: "காய்கறிகள்",
        fruits: "பழங்கள்",
        spices: "மசாலாப் பொருட்கள்",
      },
      landholdingCategory: "நிலவுடைமை வகை",
      selectCategory: "வகையைத் தேர்ந்தெடுக்கவும்",
      landCategories: {
        marginal: "விளிம்புநிலை (<1 ஹெக்டேர்)",
        small: "சிறியது (1-2 ஹெக்டேர்)",
        semiMedium: "அரை-நடுத்தர (2-4 ஹெக்டேர்)",
        medium: "நடுத்தர (4-10 ஹெக்டேர்)",
        large: "பெரியது (>10 ஹெக்டேர்)",
      },
      findSchemes: "திட்டங்களைக் கண்டறி",
      totalSchemesFound: "மொத்த திட்டங்கள் கண்டறியப்பட்டன",
      fullyEligible: "முழு தகுதி",
      partialEligibility: "பகுதி தகுதி",
      resultsExplanation: "உங்கள் வழங்கப்பட்ட சுயவிவர தகவலின் அடிப்படையில் பின்வரும் திட்டங்கள் பொருந்தும்.",
      applicableSchemes: "பொருந்தக்கூடிய திட்டங்கள்",
      schemeName: "திட்டப் பெயர்",
      ministry: "அமைச்சகம்/துறை",
      keyBenefit: "முக்கிய பலன்",
      eligibility: "தகுதி",
      eligibilityTooltip: "தகுதி முன்வரையறுக்கப்பட்ட திட்ட அளவுகோல்களைப் பயன்படுத்தி தீர்மானிக்கப்படுகிறது.",
      eligible: "முழு தகுதி",
      partial: "பகுதி தகுதி",
      schemeDetails: "திட்ட விவரங்கள் & தகுதி விளக்கம்",
      categoryLabel: "வகை",
      eligibilityNotesLabel: "தகுதி குறிப்புகள்",
      whyApplies: "இந்த திட்டம் உங்களுக்கு ஏன் பொருந்தும்:",
      keyBenefits: "முக்கிய பலன்கள்:",
      applicationProcess: "விண்ணப்ப செயல்முறை:",
      noSearch: "தேடல் செய்யப்படவில்லை",
      noSearchDesc: "மேலே உங்கள் மாநிலம், பயிர் வகை மற்றும் நிலவுடைமை வகையைத் தேர்ந்தெடுத்து, பொருந்தக்கூடிய அரசு திட்டங்களைக் காண \"திட்டங்களைக் கண்டறி\" என்பதைக் கிளிக் செய்யவும்.",
      advisorySummaryTitle: "ஆலோசனை சுருக்கம்",
      advisorySummaryIntro: "உங்கள் சுயவிவரத்தின் அடிப்படையில், பட்டியலிடப்பட்ட திட்டங்கள் உங்கள் விவசாய நடவடிக்கைகளுக்கு ஆதரவை வழங்கலாம்.",
      advisoryEligibleNote: "உங்கள் சுயவிவரத்துடன் நேரடியாகப் பொருந்தும் {count} திட்டங்களுக்கு நீங்கள் முழு தகுதி பெற்றதாகத் தெரிகிறது.",
      advisoryCategoriesNote: "இந்த திட்டங்கள் {categories} போன்ற பகுதிகளை உள்ளடக்கியது.",
      advisoryDisclaimer: "ஒவ்வொரு திட்டத்தின் விவரங்களையும் மதிப்பாய்வு செய்து, விண்ணப்ப வழிகாட்டுதலுக்கு உங்கள் உள்ளூர் விவசாய அலுவலகத்தை அணுகுமாறு பரிந்துரைக்கிறோம்.",
      advisoryNote: "இந்த சுருக்கம் தகவல் நோக்கங்களுக்காக மட்டுமே மற்றும் பலன்களின் உரிமை அல்லது உத்தரவாதத்தை உருவாக்காது.",
    },
    // Settings
    settings: {
      title: "அமைப்புகள்",
      description: "உங்கள் பண்ணை சுயவிவரம் மற்றும் விருப்பத்தேர்வுகளை நிர்வகிக்கவும்",
      accountInfo: "கணக்கு தகவல்",
      emailAddress: "மின்னஞ்சல் முகவரி",
      accountCreated: "கணக்கு உருவாக்கப்பட்டது",
      farmContext: "பண்ணை சூழல்",
      state: "மாநிலம்",
      selectState: "மாநிலத்தைத் தேர்ந்தெடுக்கவும்",
      district: "மாவட்டம்",
      enterDistrict: "மாவட்டத்தை உள்ளிடவும்",
      farmingSeason: "விவசாய பருவம்",
      selectSeason: "பருவத்தைத் தேர்ந்தெடுக்கவும்",
      landholdingSize: "நிலவுடைமை அளவு",
      selectSize: "அளவைத் தேர்ந்தெடுக்கவும்",
      primaryCrops: "முதன்மை ஆர்வமுள்ள பயிர்கள்",
      selected: "தேர்ந்தெடுக்கப்பட்டது",
      saveChanges: "மாற்றங்களைச் சேமி",
      saving: "சேமிக்கிறது...",
      profileNote: "உங்கள் சுயவிவர தகவலின் அடிப்படையில், பரிந்துரைகள் மற்றும் நுண்ணறிவுகள் உங்கள் பண்ணை சூழலுக்கு தனிப்பயனாக்கப்பட்டுள்ளன.",
      seasons: {
        kharif: "காரிஃப் (மழைக்காலம்)",
        rabi: "ரபி (குளிர்காலம்)",
        zaid: "ஜாய்த் (கோடைகாலம்)",
      },
    },
    // Common
    common: {
      loading: "ஏற்றுகிறது...",
      error: "பிழை",
      success: "வெற்றி",
      cancel: "ரத்துசெய்",
      save: "சேமி",
      language: "மொழி",
      interfaceLanguage: "இடைமுக மொழி",
    },
    // Status Labels
    status: {
      healthy: "ஆரோக்கியம்",
      attention: "கவனம் தேவை",
      risk: "ஆபத்தில்",
      high: "உயர்",
      medium: "நடுத்தர",
      low: "குறைந்த",
    },
  },
  te: {
    // App Navigation - Telugu
    nav: {
      dashboard: "డాష్‌బోర్డ్",
      cropRecommendation: "పంట సిఫార్సు",
      diseaseDetection: "వ్యాధి గుర్తింపు",
      governmentSchemes: "ప్రభుత్వ పథకాలు",
      settings: "సెట్టింగ్‌లు",
      signOut: "లాగ్ అవుట్",
    },
    // Sidebar
    sidebar: {
      appName: "అగ్రోగైడ్",
      tagline: "వ్యవసాయ నిర్ణయ మద్దతు వేదిక",
      loggedInAs: "లాగిన్ అయినది",
      version: "వెర్షన్ 1.0",
      collegeProject: "కళాశాల ప్రధాన ప్రాజెక్ట్",
      agricultureTech: "వ్యవసాయ సాంకేతికత",
      navDescriptions: {
        dashboard: "అవలోకనం & సారాంశం",
        cropRecommendation: "పంట ఎంపిక సలహా",
        diseaseDetection: "ఆరోగ్య అంచనా",
        governmentSchemes: "పథక అర్హత",
        settings: "ప్రొఫైల్ & ప్రాధాన్యతలు",
      },
    },
    // Dashboard
    dashboard: {
      title: "డాష్‌బోర్డ్",
      description: "మీ ప్రొఫైల్ ఆధారంగా ప్రస్తుత స్థితి మరియు చర్య అంతర్దృష్టులు",
      location: "స్థానం",
      season: "సీజన్",
      interest: "ఆసక్తి",
      land: "భూమి",
      currentRecommendation: "ప్రస్తుత సిఫార్సు",
      suitability: "అనుకూలత",
      expectedYield: "అంచనా దిగుబడి",
      estReturns: "అంచనా రాబడి",
      cropHealth: "పంట ఆరోగ్యం",
      schemes: "పథకాలు",
      available: "అందుబాటులో",
      fullyEligible: "పూర్తి అర్హత",
      recentRecommendations: "ఇటీవలి సిఫార్సులు",
      fieldHealthSummary: "పొలం ఆరోగ్య సారాంశం",
      healthy: "ఆరోగ్యకరం",
      attention: "శ్రద్ధ",
      atRisk: "ప్రమాదంలో",
      pending: "పెండింగ్",
      profileNote: "మీ ప్రొఫైల్ సమాచారం ఆధారంగా — సిఫార్సులు మీ వ్యవసాయ సందర్భానికి వ్యక్తిగతీకరించబడ్డాయి",
      noProfileMessage: "వ్యక్తిగతీకరించిన అంతర్దృష్టులను చూడటానికి దయచేసి మీ ప్రొఫైల్ సెటప్‌ను పూర్తి చేయండి.",
      goToSettings: "సెట్టింగ్‌లకు వెళ్ళండి",
      loading: "డాష్‌బోర్డ్ లోడ్ అవుతోంది...",
      seasons: {
        kharif: "ఖరీఫ్ (వర్షాకాలం)",
        rabi: "రబీ (శీతాకాలం)",
        zaid: "జాయద్ (వేసవి)",
      },
    },
    // Crop Recommendation
    cropRec: {
      title: "పంట సిఫార్సు",
      description: "మీ నిర్దిష్ట పరిస్థితికి అనుకూలమైన పంట ఎంపిక మార్గదర్శకత్వం పొందడానికి పొలం పరిస్థితులను అందించండి",
      soilParams: "నేల పరిస్థితి పారామీటర్లు",
      soilType: "నేల రకం",
      selectSoilType: "నేల రకం ఎంచుకోండి",
      soilTypes: {
        clay: "బంకమట్టి",
        sandy: "ఇసుక నేల",
        loamy: "గుల్ల నేల",
        black: "నల్ల పత్తి నేల",
        red: "ఎర్ర నేల",
        alluvial: "ఒండ్రు నేల",
      },
      soilPh: "నేల pH స్థాయి",
      nitrogen: "నత్రజని (కిగ్రా/హె)",
      phosphorus: "భాస్వరం (కిగ్రా/హె)",
      potassium: "పొటాషియం (కిగ్రా/హె)",
      weatherLocation: "వాతావరణం & స్థానం",
      avgRainfall: "సగటు వర్షపాతం (మిమీ)",
      temperature: "ఉష్ణోగ్రత (°C)",
      humidity: "తేమ (%)",
      region: "ప్రాంతం",
      selectRegion: "ప్రాంతం ఎంచుకోండి",
      regions: {
        central: "మధ్య భారతదేశం",
        north: "ఉత్తర భారతదేశం",
        south: "దక్షిణ భారతదేశం",
        east: "తూర్పు భారతదేశం",
        west: "పశ్చిమ భారతదేశం",
        northeast: "ఈశాన్య భారతదేశం",
      },
      getRecommendation: "సిఫార్సు పొందండి",
      analyzing: "విశ్లేషిస్తోంది...",
      recommendedCrop: "సిఫార్సు చేయబడిన పంట",
      highSuitability: "అధిక అనుకూలత",
      mediumSuitability: "మధ్యస్థ అనుకూలత",
      estProfitability: "అంచనా లాభదాయకత",
      whyRecommended: "ఈ పంట ఎందుకు సిఫార్సు చేయబడింది",
      alternatives: "ప్రత్యామ్నాయ ఎంపికలు",
      noRecommendation: "ఇంకా సిఫార్సు లేదు",
      noRecommendationDesc: "ఎడమవైపు నేల మరియు వాతావరణ పారామీటర్లను నింపండి, తర్వాత మీ పరిస్థితులకు అనుకూలమైన పంట సిఫార్సులు పొందడానికి సమర్పించండి.",
      range: "పరిధి: 0-14",
    },
    // Disease Detection
    disease: {
      title: "పంట వ్యాధి గుర్తింపు",
      description: "సమగ్ర పొలం విశ్లేషణ కోసం స్మార్ట్‌ఫోన్ చిత్రాలు లేదా డ్రోన్ చిత్రాలను ఉపయోగించి పంట ఆరోగ్యాన్ని అంచనా వేయండి",
      smartphoneCamera: "స్మార్ట్‌ఫోన్ కెమెరా",
      droneAssessment: "డ్రోన్ అంచనా",
      imageAnalysis: "చిత్ర విశ్లేషణ",
      cropType: "పంట రకం (ఐచ్ఛికం)",
      selectCrop: "సందర్భోచిత విశ్లేషణ కోసం పంట ఎంచుకోండి",
      cropContextHelp: "పంట ఎంచుకోవడం సందర్భ-అవగాహన సిఫార్సులు అందించడంలో సహాయపడుతుంది",
      uploadImage: "పంట చిత్రం అప్‌లోడ్ చేయండి",
      uploadHint: "ప్రభావిత మొక్క భాగం యొక్క స్పష్టమైన ఫోటో తీయండి",
      supported: "మద్దతు ఉంది: JPG, PNG (గరిష్టం 10MB)",
      clickToReplace: "చిత్రం మార్చడానికి క్లిక్ చేయండి",
      analyzeImage: "చిత్రం విశ్లేషించండి",
      newAnalysis: "కొత్త విశ్లేషణ",
      assessmentResult: "అంచనా ఫలితం",
      cropAppears: "పంట ఆరోగ్యంగా కనిపిస్తోంది",
      crop: "పంట",
      issueCategory: "సమస్య వర్గం",
      affectedArea: "ప్రభావిత ప్రాంతం",
      expertAdvisory: "నిపుణుల సలహా",
      understanding: "అవగాహన",
      awaitingImage: "చిత్రం కోసం వేచి ఉంది",
      awaitingImageDesc: "మీ పంట యొక్క స్పష్టమైన చిత్రాన్ని అప్‌లోడ్ చేసి వివరమైన ఆరోగ్య అంచనా పొందడానికి \"చిత్రం విశ్లేషించండి\" క్లిక్ చేయండి.",
      fieldHealthOverview: "పొలం ఆరోగ్య అవలోకనం",
      startDrone: "పొలం అంచనా ప్రారంభించు",
      analyzingField: "పొలం విశ్లేషిస్తోంది...",
      zoneStatus: "జోన్ స్థితి",
      affectedPercentage: "ప్రభావిత ప్రాంతం",
      riskZones: "ప్రమాద జోన్లు",
      zonesPossible: "సాధ్యమైన సమస్యలు ఉన్న జోన్లు",
      identifiedConcerns: "గుర్తించిన ఆందోళనలు",
      needsAttention: "శ్రద్ధ అవసరం",
      underMonitoring: "పర్యవేక్షణలో",
      immediateInspection: "తక్షణ పొలం తనిఖీ సిఫార్సు చేయబడింది",
      monitorPreventive: "పర్యవేక్షించండి మరియు నివారణ చర్యలు పరిగణించండి",
      nextSteps: "సిఫార్సు చేయబడిన తదుపరి దశలు",
      conductInspection: "B3, A3, మరియు C3 జోన్లలో భౌతిక తనిఖీ నిర్వహించండి",
      collectSamples: "అవసరమైతే ప్రయోగశాల నిర్ధారణ కోసం ఆకు నమూనాలు సేకరించండి",
      consultExpert: "చికిత్స ఎంపికల కోసం వ్యవసాయ విస్తరణ అధికారిని సంప్రదించండి",
      noDisease: "వ్యాధి కనుగొనబడలేదు",
      healthyMessage: "మీ పంట ఆరోగ్యంగా కనిపిస్తోంది. ప్రస్తుత వ్యవసాయ పద్ధతులు కొనసాగించండి.",
      severity: {
        low: "తక్కువ తీవ్రత",
        medium: "మధ్యస్థ తీవ్రత",
        high: "అధిక తీవ్రత",
      },
      categories: {
        fungal: "శిలీంధ్రం",
        bacterial: "బ్యాక్టీరియా",
        viral: "వైరల్",
        pest: "పురుగు",
        healthy: "ఆరోగ్యకరం",
        nutrient: "పోషకాల లోపం",
        water: "నీటి ఒత్తిడి",
      },
      crops: {
        rice: "వరి",
        wheat: "గోధుమ",
        maize: "మొక్కజొన్న",
        cotton: "పత్తి",
        tomato: "టమాటా",
        potato: "బంగాళాదుంప",
        sugarcane: "చెరకు",
        groundnut: "వేరుశెనగ",
        soybean: "సోయాబీన్",
        other: "ఇతర పంట",
      },
    },
    // Government Schemes
    schemes: {
      title: "ప్రభుత్వ పథక అర్హత & సలహా",
      subtitle: "రైతు ప్రొఫైల్ ఆధారంగా వర్తించే వ్యవసాయ పథకాల నియమ-ఆధారిత గుర్తింపు",
      description: "మీ ప్రొఫైల్ మరియు వ్యవసాయ కార్యకలాపాల ఆధారంగా సంబంధిత ప్రభుత్వ పథకాలను గుర్తించండి",
      filterCriteria: "రైతు ప్రొఫైల్ పారామీటర్లు",
      filterHelperText: "ఎంచుకున్న రాష్ట్రం, పంట రకం మరియు భూ హోల్డింగ్ వర్గం ఆధారంగా పథకాలు గుర్తించబడతాయి.",
      state: "రాష్ట్రం",
      selectState: "రాష్ట్రం ఎంచుకోండి",
      cropType: "పంట రకం",
      selectCrop: "పంట ఎంచుకోండి",
      cropTypes: {
        cereals: "ధాన్యాలు (వరి, గోధుమ)",
        pulses: "పప్పు దినుసులు",
        oilseeds: "నూనె గింజలు (సోయాబీన్, వేరుశెనగ)",
        cotton: "పత్తి",
        sugarcane: "చెరకు",
        vegetables: "కూరగాయలు",
        fruits: "పండ్లు",
        spices: "మసాలా దినుసులు",
      },
      landholdingCategory: "భూ హోల్డింగ్ వర్గం",
      selectCategory: "వర్గం ఎంచుకోండి",
      landCategories: {
        marginal: "చిన్న భూమి (<1 హెక్టార్)",
        small: "చిన్న (1-2 హెక్టార్లు)",
        semiMedium: "సెమీ-మీడియం (2-4 హెక్టార్లు)",
        medium: "మధ్యస్థ (4-10 హెక్టార్లు)",
        large: "పెద్ద (>10 హెక్టార్లు)",
      },
      findSchemes: "పథకాలు కనుగొనండి",
      totalSchemesFound: "మొత్తం పథకాలు కనుగొనబడ్డాయి",
      fullyEligible: "పూర్తి అర్హత",
      partialEligibility: "పాక్షిక అర్హత",
      resultsExplanation: "మీ అందించిన ప్రొఫైల్ సమాచారం ఆధారంగా కింది పథకాలు వర్తిస్తాయి.",
      applicableSchemes: "వర్తించే పథకాలు",
      schemeName: "పథకం పేరు",
      ministry: "మంత్రిత్వ శాఖ/విభాగం",
      keyBenefit: "ముఖ్య ప్రయోజనం",
      eligibility: "అర్హత",
      eligibilityTooltip: "అర్హత ముందుగా నిర్వచించిన పథక ప్రమాణాలను ఉపయోగించి నిర్ణయించబడుతుంది.",
      eligible: "పూర్తి అర్హత",
      partial: "పాక్షిక అర్హత",
      schemeDetails: "పథక వివరాలు & అర్హత వివరణ",
      categoryLabel: "వర్గం",
      eligibilityNotesLabel: "అర్హత నోట్లు",
      whyApplies: "ఈ పథకం మీకు ఎందుకు వర్తిస్తుంది:",
      keyBenefits: "ముఖ్య ప్రయోజనాలు:",
      applicationProcess: "దరఖాస్తు ప్రక్రియ:",
      noSearch: "శోధన జరగలేదు",
      noSearchDesc: "పైన మీ రాష్ట్రం, పంట రకం మరియు భూ హోల్డింగ్ వర్గం ఎంచుకోండి, తర్వాత వర్తించే ప్రభుత్వ కార్యక్రమాలను చూడటానికి \"పథకాలు కనుగొనండి\" క్లిక్ చేయండి.",
      advisorySummaryTitle: "సలహా సారాంశం",
      advisorySummaryIntro: "మీ ప్రొఫైల్ ఆధారంగా, జాబితా చేయబడిన పథకాలు మీ వ్యవసాయ కార్యకలాపాలకు మద్దతు అందించవచ్చు.",
      advisoryEligibleNote: "మీ ప్రొఫైల్‌తో నేరుగా సరిపోయే {count} పథకాలకు మీరు పూర్తి అర్హత కలిగి ఉన్నట్లు కనిపిస్తోంది.",
      advisoryCategoriesNote: "ఈ పథకాలు {categories} వంటి ప్రాంతాలను కవర్ చేస్తాయి.",
      advisoryDisclaimer: "ప్రతి పథకం వివరాలను సమీక్షించి, దరఖాస్తు మార్గదర్శకత్వం కోసం మీ స్థానిక వ్యవసాయ కార్యాలయాన్ని సంప్రదించమని సిఫార్సు చేస్తున్నాము.",
      advisoryNote: "ఈ సారాంశం సమాచార ప్రయోజనాల కోసం మాత్రమే మరియు ప్రయోజనాల హక్కు లేదా హామీని కలిగి ఉండదు.",
    },
    // Settings
    settings: {
      title: "సెట్టింగ్‌లు",
      description: "మీ వ్యవసాయ ప్రొఫైల్ మరియు ప్రాధాన్యతలను నిర్వహించండి",
      accountInfo: "ఖాతా సమాచారం",
      emailAddress: "ఇమెయిల్ చిరునామా",
      accountCreated: "ఖాతా సృష్టించబడింది",
      farmContext: "వ్యవసాయ సందర్భం",
      state: "రాష్ట్రం",
      selectState: "రాష్ట్రం ఎంచుకోండి",
      district: "జిల్లా",
      enterDistrict: "జిల్లా నమోదు చేయండి",
      farmingSeason: "వ్యవసాయ సీజన్",
      selectSeason: "సీజన్ ఎంచుకోండి",
      landholdingSize: "భూ హోల్డింగ్ పరిమాణం",
      selectSize: "పరిమాణం ఎంచుకోండి",
      primaryCrops: "ప్రధాన ఆసక్తి పంటలు",
      selected: "ఎంచుకున్నవి",
      saveChanges: "మార్పులు సేవ్ చేయండి",
      saving: "సేవ్ అవుతోంది...",
      profileNote: "మీ ప్రొఫైల్ సమాచారం ఆధారంగా, సిఫార్సులు మరియు అంతర్దృష్టులు మీ వ్యవసాయ సందర్భానికి వ్యక్తిగతీకరించబడ్డాయి.",
      seasons: {
        kharif: "ఖరీఫ్ (వర్షాకాలం)",
        rabi: "రబీ (శీతాకాలం)",
        zaid: "జాయద్ (వేసవి)",
      },
    },
    // Common
    common: {
      loading: "లోడ్ అవుతోంది...",
      error: "లోపం",
      success: "విజయం",
      cancel: "రద్దు చేయండి",
      save: "సేవ్ చేయండి",
      language: "భాష",
      interfaceLanguage: "ఇంటర్‌ఫేస్ భాష",
    },
    // Status Labels
    status: {
      healthy: "ఆరోగ్యకరం",
      attention: "శ్రద్ధ అవసరం",
      risk: "ప్రమాదంలో",
      high: "అధిక",
      medium: "మధ్యస్థ",
      low: "తక్కువ",
    },
  },
};
